name: publish to pypi

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: install poetry
        env:
          POETRY_VERSION: "1.7.1"
        run: curl -sSL https://install.python-poetry.org | python -

      - name: build python package
        run: poetry build

      - name: publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
